server:
  port: 8011
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nba
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:data.sql #classpath: data.sql,file:src/main/resources/data.sql
    continue-on-error: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update